version: '3.8'

services:
  service:
    build:
      context: .
    environment:
      - SPRING_CONFIG_LOCATION=/config/
    ports:
      - 9000:9000
    volumes:
      - ./logs:/logs
      - ./application-local.yml:/config/application.yml
