info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    path: logs
  level:
    edu.harvard.drs: DEBUG
    org.springframework: INFO
    web: INFO

management:
  endpoint:
    health:
      enabled: true
      showDetails: always
    info:
      enabled: true
    logfile:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, logfile

server:
  port: 9000
  servlet:
    context-path:

spring:
  application:
    name: DRS Verify
  profiles:
    active: development
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  devtools:
    addProperties: true
    livereload:
      enabled: true

  main:
    lazyInitialization: true
